live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "term-256color"

[font]
size = 18

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "Transparent"
opacity = 0.97
[window.padding]
x = 10
y = 30
